version: "3.8"

services:
  mysql:
    image: mysql:8.0.23
    environment:
      MYSQL_DATABASE: puresynth
      MYSQL_USER: puresynth
      MYSQL_PASSWORD: puresynth
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data:
    driver: local
