version: "3.8"

services:
  mysql:
    image: mysql:8.0.23
    environment:
      MYSQL_DATABASE: 'yourdbname'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  app:
    image: your-spring-boot-app:latest
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/yourdbname?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    restart: always

  flyway:
    image: flyway/flyway
    command: [ "-url=jdbc:mysql://db:3306/puresynth?allowPublicKeyRetrieval=true&useSSL=false", "-user=puresynth", "-password=puresynth", "clean", "migrate" ]
    environment:
      - FLYWAY_CLEAN_DISABLED=false
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - db

volumes:
  mysql-data:
    driver: local