version: "3.8"

services:

  db:
    image: mysql:8.0.23
    restart: always
    environment:
      MYSQL_DATABASE: puresynth
      MYSQL_USERNAME: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"


