version: "3.8"

services:
  mysql:
    image: mysql:8.0.23
    environment:
      MYSQL_DATABASE: 'yourdbname'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  app:
    image: your-spring-boot-app:latest
    depends_on:
      - mysql
    environment:
      MYSQL_DATABASE: puresynth
      MYSQL_USER: puresynth
      MYSQL_PASSWORD: puresynth
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "8080:8080"
    restart: always

volumes:
  mysql-data:
    driver: local
